### ISSUE TITLE
Doesn't compile with gcc 4.5.1/Qt 4.7

### ISSUE THREAD

**Issue by ghost** [minimoog/QTweetLib#2]
oauth.cpp:85:15: error: #elif with no expression

Reason is Qt does
# define Q_WS_X11

(without defining it to any value, therefore "#elif Q_WS_X11" expands to "#elif ")

You want to use
# elif defined(Q_WS_X11)

instead of
# elif Q_WS_X11.

Also, it would probably be better to replace Q_WS_WIN with Q_OS_WIN (this is about the OS, not the windowing system...) and to just use a generic #else (The assumptions about OpenSSL are equally valid for Qt for Embedded Linux, which has Q_WS_QWS instead of Q_WS_X11).

**Comment by minimoog** [comment]
Thanks for reporting and most important, fixing the bug.

I changed Q_WS_WIN to Q_OS_WIN and instead #elif there is #else.
